create database member;
CREATE TABLE member.tm_member (
	`MEMBER_ID` VARCHAR(32) NOT NULL COMMENT '会员ID(由seq_member_id 生成, 个人1开头，企业2开头)',
	`MEMBER_NAME` VARCHAR(255) NULL DEFAULT NULL COMMENT '会员名称',
	`MEMBER_SHORT_NAME` VARCHAR(60) NULL DEFAULT NULL COMMENT '会员缩略名,已注销的会被添加后缀',
	`MEMBER_TYPE` DECIMAL(8,0) NOT NULL COMMENT '会员类型(1个人 2 公司 3 组织)',
	`STATUS` DECIMAL(8,0) NOT NULL COMMENT '会员状态(0未激活 1正常 2休眠 3注销)',
	`LOCK_STATUS` DECIMAL(8,0) NOT NULL COMMENT '会员锁定状态(0未锁定 1已锁定)',
	`FROM_IP` VARCHAR(30) NULL DEFAULT NULL COMMENT 'IP地址',
	`ACTIVE_TIME` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '激活时间',
	`CREATE_TIME` TIMESTAMP NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT '建立时间',
	`UPDATE_TIME` TIMESTAMP NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT '更新时间',
	`CREATE_USER` VARCHAR(50) NULL DEFAULT NULL COMMENT '建立人',
	`UPDATE_USER` VARCHAR(50) NULL DEFAULT NULL COMMENT '更新人',
	`MEMO` VARCHAR(255) NULL DEFAULT NULL COMMENT '备注信息',
	`SECURITY_LEVEL` VARCHAR(50) NULL DEFAULT '0' COMMENT '安全等级',
	`trade_limit` DECIMAL(15,2) NOT NULL DEFAULT '0.00' COMMENT '免密限额',
	PRIMARY KEY (`MEMBER_ID`)
)
COMMENT='会员信息表'
COLLATE='utf8_general_ci'
ENGINE=InnoDB;
